### PR TITLE
Fix jump to file error

### LINKED ISSUE #88: Cannot jump to file
If i click on a file inside the search-result view i get the following error message on the browsers debug console:
```
Uncaught TypeError: Cannot set property 'currentFile' of undefined
    at FullTextSearch.onEntrySelected (files.js?v=cdf36c83-11:266)
    at Object.onEntrySelected (fulltextsearch.v1.navigation.js?v=cdf36c83-11:277)
    at HTMLDivElement.<anonymous> (fulltextsearch.v1.navigation.js?v=cdf36c83-11:237)
    at HTMLDivElement.dispatch (jquery.js:4435)
    at HTMLDivElement._.handle (jquery.js:4121)
```
This only happens from the search popup (top right or Ctrl + F) but not if i use the full search interface (top left search icon).

- **App Version:** 1.4.1
- **Nextcloud Version:** 18

### PR DESCRIPTION
**Pull request by R0Wi**
Fix #88

### CODE REVIEW

**Comment by hashworks** [comment]
While for me the error is gone with this fix, clicking on files still does nothing.

**Comment by R0Wi** [comment]
@hashworks do you mean you're not seeing the error in the console anymore but the click on a search- result still doesn't jump to the file? Which version of nextcloud do you use?

**Comment by hashworks** [comment]
Exactly. 19 – so yeah, could be because of that.

**Comment by R0Wi** [comment]
Did a quick setup with NC 19 but for me it's still working. So if there's a default-fileaction registered by any app (e.g. for viewing an image) this one opens. Otherwise a new tab is opened and you're navigated to the folder containing the file and the file is then focussed afterwards. Do you see any other errors showing up in your console? And could you try to search for a file with a special mimetype where no default app is registered an click on that one (e.g. a word-document if you haven't installed Collabora or something else. So a filetype which would usually be downloaded and not opened inside NC)?

**Comment by hashworks** [comment]
Just checked, stuff like Markdown or Image files work fine. The files that fail to open are `docx`, which should be opened in Collabora – as I mentioned before, that might be related to #83, not this issue :)

Besides the general `$ is deprecated` warnings I get no console messages. There are no network connections either.

**Comment by R0Wi** [comment]
I see :-) What i observed is that the fulltext app provides less information about the clicked file than the regular files view. So the solution of https://github.com/nextcloud/files_photospheres/issues/52 might also be interesting by the way.

**Comment by R0Wi** [comment]
Seems to be fixed in newer versions of NC without changing the code. Closing

**Pull request closed without merging**
