### PR TITLE
Add Option to Open Files Directly from Search Results

### PR DESCRIPTION
**Pull request by And0r-**
The ability to open a file directly from search results, as requested in [Issue #249](https://github.com/nextcloud/files_fulltextsearch/issues/249), is a very useful feature. This idea was initially proposed by [ostasevych](https://github.com/ostasevych) in [Pull Request #250](https://github.com/nextcloud/files_fulltextsearch/pull/250).

I've implemented this feature and added an option to the plugin settings. By default, the current behavior remains unchanged. However, users now have the choice to enable direct opening of files from search results. This enhancement aims to improve user experience by providing a more efficient way to access files through search.

Please review the changes and consider merging them into the main project. Thank you for your consideration!

### CODE REVIEW

**Comment by And0r-** [comment]
I wanted to provide a quick update on this PR. I've noticed that the implemented method for directly opening files from search results may not be functioning as expected in Nextcloud version 28. I am currently investigating this issue to better understand why this is happening and to find a suitable solution.

I will update this PR with any new findings or necessary code adjustments as soon as possible. Meanwhile, I appreciate your patience and welcome any feedback or suggestions from the community.

**Comment by And0r-** [comment]
I'm pleased to provide an update on this Pull Request. After further investigation, I discovered that the initial method for opening files directly from search results needed an adjustment for compatibility with Nextcloud version 28.

I have now updated the implementation to align with the method used in Nextcloud's official `FilesSearchProvider.php`. The revised approach utilizes the `files.View.showFile` route to generate links, ensuring compatibility with Nextcloud 28:

```php
$link = $this->urlGenerator->linkToRoute('files.View.showFile', ['fileid' => $document->getId()]);
```

This change should resolve the issues observed with Nextcloud 28, and the feature now functions as intended across different Nextcloud versions. I have tested this thoroughly to ensure its reliability and compatibility.

I believe this update will enhance the user experience by providing a more efficient way to access files directly from search results. Your review and feedback on these changes would be greatly appreciated.

**Comment by And0r-** [comment]
Hi @ArtificialOwl,
The PR has been open for a long time now; are there any issues with it, or is there anything I can do to make the review process easier? I am willing to invest another 2-3 weekends if needed.
So just let me know if you would prefer the feature to be implemented differently.

Alternatively, if the feature won't be merged because there's not enough interest, it would be helpful to know. In that case, I'll create a userscript workaround for myself to remain update-capable.

**Comment by DaphneMuller** [comment]
@ArtificialOwl is this pull request still on your radar? If you don't have time for it, could you please raise it to Stephan?

**Review by ArtificialOwl — APPROVED** [review]

**Pull request merged**
