### PR TITLE
using UserGlobalStoragesService

### PR DESCRIPTION
**Pull request by daita**

### CODE REVIEW

**Comment by daita** [comment]
can you confirm that the content from those remote files is indexed ?

**Comment by daita** [comment]
if you have the ID of the file, you can use `./occ fulltextsearch:document:provider` or `./occ fulltextsearch:document:platform`

**Comment by truelai** [comment]
> if you have the ID of the file, you can use `./occ fulltextsearch:document:provider` or `./occ fulltextsearch:document:platform`

Can you tell me how I can find the ID of a file?

**Comment by truelai** [comment]
> can you confirm that the content from those remote files is indexed ?

Not yet. I did a search on a scanned doc but nothing returned on the search. I'll update tomorrow.

**Comment by daita** [comment]
the easiest way is to open the details of a document in the web client, and click on the icon that generate a link: 

Selection_071

This should returns an URL and the last integer is the Id of the file

**Comment by truelai** [comment]
> > can you confirm that the content from those remote files is indexed ?
> 
> Not yet. I did a search on a scanned doc but nothing returned on the search. I'll update tomorrow.

Checked this morning - it appears the content is not being indexed.

**Comment by daita** [comment]
Ok, might have found the issue. Could you try again the PR and create or get the ID of an existing file and use this command ?

`./occ fulltextsearch:document:provider <your_username> files <file_id> --content`

You should see the first few character of the content, meaning that FullTextSearch is able to reach the content of this file.

**Comment by truelai** [comment]
> Ok, might have found the issue. Could you try again the PR and create or get the ID of an existing file and use this command ?
> 
> `./occ fulltextsearch:document:provider <your_username> files <file_id> --content`
> 
> You should see the first few character of the content, meaning that FullTextSearch is able to reach the content of this file.



> Ok, might have found the issue. Could you try again the PR and create or get the ID of an existing file and use this command ?
> 
> `./occ fulltextsearch:document:provider <your_username> files <file_id> --content`
> 
> You should see the first few character of the content, meaning that FullTextSearch is able to reach the content of this file.

Here's the end out the output:
```

    },
    "hash": "",
    "contentSize": 183000,
    "tags": [],
    "metatags": [
        "files_external"
    ],
    "subtags": [],
    "more": [],
    "excerpts": [],
    "score": ""
}
Content: 
%PDF-1.7
%����
2 0 obj
<< /Linearized 1
/L 137248
/O 13
/E 137133
/N 1
/
1 Part(s)
'comments'    (size: 0)

```

**Comment by daita** [comment]
ok, looking good. thanks !

**Comment by truelai** [comment]
My pleasure.

**Pull request merged**
