### PR TITLE
Add drawio support

### PR DESCRIPTION
**Pull request by masahirominami**
I wanted to experiment on the issue #21 , and here's my first try.
With this code .xml and .drawio files can be indexed.

If anyone is interested, any feedback will be welcome. Thank you.

### CODE REVIEW

**Comment by ArtificialOwl** [comment]
Hello and thanks for your PR.

Can you share some files to test this ?

**Comment by masahirominami** [comment]
Hi, thank you for the comment. Added test.xml and test.drawio along with the other existing "test.*" files, is this what you expected ? They should be found with keywords like "test-", "test-key", "test-value", "test-success". Draw.io format's sheet names are currently ignored.

**Comment by ArtificialOwl** [comment]
Looks good, can you rebase on `master` ?

**Review by ArtificialOwl — APPROVED** [review]

**Pull request merged**
